#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Bit.Android.Resource", IsApplication=true)]

namespace Bit.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::Bit.Android.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::Bit.Android.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::Bit.Android.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::Bit.Android.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::Bit.Android.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::Bit.Android.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::Bit.Android.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::Bit.Android.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::Bit.Android.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::Bit.Android.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::Bit.Android.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::Bit.Android.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::Bit.Android.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::Bit.Android.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::Bit.Android.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::Bit.Android.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::Bit.Android.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::Bit.Android.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::Bit.Android.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::Bit.Android.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::Bit.Android.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::Bit.Android.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::Bit.Android.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::Bit.Android.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::Bit.Android.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::Bit.Android.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::Bit.Android.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::Bit.Android.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::Bit.Android.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::Bit.Android.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::Bit.Android.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::Bit.Android.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::Bit.Android.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::Bit.Android.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::Bit.Android.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::Bit.Android.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::Bit.Android.Resource.Styleable.ProgressWheel_ahTextSize;
			global::HockeyApp.Resource.Color.hockeyapp_background_header = global::Bit.Android.Resource.Color.hockeyapp_background_header;
			global::HockeyApp.Resource.Color.hockeyapp_background_light = global::Bit.Android.Resource.Color.hockeyapp_background_light;
			global::HockeyApp.Resource.Color.hockeyapp_background_white = global::Bit.Android.Resource.Color.hockeyapp_background_white;
			global::HockeyApp.Resource.Color.hockeyapp_button_background = global::Bit.Android.Resource.Color.hockeyapp_button_background;
			global::HockeyApp.Resource.Color.hockeyapp_button_background_pressed = global::Bit.Android.Resource.Color.hockeyapp_button_background_pressed;
			global::HockeyApp.Resource.Color.hockeyapp_button_background_selected = global::Bit.Android.Resource.Color.hockeyapp_button_background_selected;
			global::HockeyApp.Resource.Color.hockeyapp_text_black = global::Bit.Android.Resource.Color.hockeyapp_text_black;
			global::HockeyApp.Resource.Color.hockeyapp_text_light = global::Bit.Android.Resource.Color.hockeyapp_text_light;
			global::HockeyApp.Resource.Color.hockeyapp_text_normal = global::Bit.Android.Resource.Color.hockeyapp_text_normal;
			global::HockeyApp.Resource.Color.hockeyapp_text_white = global::Bit.Android.Resource.Color.hockeyapp_text_white;
			global::HockeyApp.Resource.Drawable.hockeyapp_btn_background = global::Bit.Android.Resource.Drawable.hockeyapp_btn_background;
			global::HockeyApp.Resource.Id.button_add_response = global::Bit.Android.Resource.Id.button_add_response;
			global::HockeyApp.Resource.Id.button_attachment = global::Bit.Android.Resource.Id.button_attachment;
			global::HockeyApp.Resource.Id.button_login = global::Bit.Android.Resource.Id.button_login;
			global::HockeyApp.Resource.Id.button_refresh = global::Bit.Android.Resource.Id.button_refresh;
			global::HockeyApp.Resource.Id.button_send = global::Bit.Android.Resource.Id.button_send;
			global::HockeyApp.Resource.Id.button_update = global::Bit.Android.Resource.Id.button_update;
			global::HockeyApp.Resource.Id.input_email = global::Bit.Android.Resource.Id.input_email;
			global::HockeyApp.Resource.Id.input_message = global::Bit.Android.Resource.Id.input_message;
			global::HockeyApp.Resource.Id.input_name = global::Bit.Android.Resource.Id.input_name;
			global::HockeyApp.Resource.Id.input_password = global::Bit.Android.Resource.Id.input_password;
			global::HockeyApp.Resource.Id.input_subject = global::Bit.Android.Resource.Id.input_subject;
			global::HockeyApp.Resource.Id.label_author = global::Bit.Android.Resource.Id.label_author;
			global::HockeyApp.Resource.Id.label_date = global::Bit.Android.Resource.Id.label_date;
			global::HockeyApp.Resource.Id.label_last_updated = global::Bit.Android.Resource.Id.label_last_updated;
			global::HockeyApp.Resource.Id.label_message = global::Bit.Android.Resource.Id.label_message;
			global::HockeyApp.Resource.Id.label_text = global::Bit.Android.Resource.Id.label_text;
			global::HockeyApp.Resource.Id.label_title = global::Bit.Android.Resource.Id.label_title;
			global::HockeyApp.Resource.Id.label_version = global::Bit.Android.Resource.Id.label_version;
			global::HockeyApp.Resource.Id.list_attachments = global::Bit.Android.Resource.Id.list_attachments;
			global::HockeyApp.Resource.Id.list_feedback_messages = global::Bit.Android.Resource.Id.list_feedback_messages;
			global::HockeyApp.Resource.Id.text_headline = global::Bit.Android.Resource.Id.text_headline;
			global::HockeyApp.Resource.Id.view_header = global::Bit.Android.Resource.Id.view_header;
			global::HockeyApp.Resource.Id.web_update_details = global::Bit.Android.Resource.Id.web_update_details;
			global::HockeyApp.Resource.Id.wrapper_attachments = global::Bit.Android.Resource.Id.wrapper_attachments;
			global::HockeyApp.Resource.Id.wrapper_feedback = global::Bit.Android.Resource.Id.wrapper_feedback;
			global::HockeyApp.Resource.Id.wrapper_feedback_scroll = global::Bit.Android.Resource.Id.wrapper_feedback_scroll;
			global::HockeyApp.Resource.Id.wrapper_messages = global::Bit.Android.Resource.Id.wrapper_messages;
			global::HockeyApp.Resource.Id.wrapper_messages_buttons = global::Bit.Android.Resource.Id.wrapper_messages_buttons;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_expiry_info = global::Bit.Android.Resource.Layout.hockeyapp_activity_expiry_info;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_feedback = global::Bit.Android.Resource.Layout.hockeyapp_activity_feedback;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_login = global::Bit.Android.Resource.Layout.hockeyapp_activity_login;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_update = global::Bit.Android.Resource.Layout.hockeyapp_activity_update;
			global::HockeyApp.Resource.Layout.hockeyapp_fragment_update = global::Bit.Android.Resource.Layout.hockeyapp_fragment_update;
			global::HockeyApp.Resource.Layout.hockeyapp_view_feedback_message = global::Bit.Android.Resource.Layout.hockeyapp_view_feedback_message;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_app_name_fallback = global::Bit.Android.Resource.String.hockeyapp_crash_dialog_app_name_fallback;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_message = global::Bit.Android.Resource.String.hockeyapp_crash_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_negative_button = global::Bit.Android.Resource.String.hockeyapp_crash_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_neutral_button = global::Bit.Android.Resource.String.hockeyapp_crash_dialog_neutral_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_positive_button = global::Bit.Android.Resource.String.hockeyapp_crash_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_title = global::Bit.Android.Resource.String.hockeyapp_crash_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_dialog_error_message = global::Bit.Android.Resource.String.hockeyapp_dialog_error_message;
			global::HockeyApp.Resource.String.hockeyapp_dialog_error_title = global::Bit.Android.Resource.String.hockeyapp_dialog_error_title;
			global::HockeyApp.Resource.String.hockeyapp_dialog_negative_button = global::Bit.Android.Resource.String.hockeyapp_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_dialog_positive_button = global::Bit.Android.Resource.String.hockeyapp_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_message = global::Bit.Android.Resource.String.hockeyapp_download_failed_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_negative_button = global::Bit.Android.Resource.String.hockeyapp_download_failed_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_positive_button = global::Bit.Android.Resource.String.hockeyapp_download_failed_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_title = global::Bit.Android.Resource.String.hockeyapp_download_failed_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_error_no_network_message = global::Bit.Android.Resource.String.hockeyapp_error_no_network_message;
			global::HockeyApp.Resource.String.hockeyapp_expiry_info_text = global::Bit.Android.Resource.String.hockeyapp_expiry_info_text;
			global::HockeyApp.Resource.String.hockeyapp_expiry_info_title = global::Bit.Android.Resource.String.hockeyapp_expiry_info_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attach_file = global::Bit.Android.Resource.String.hockeyapp_feedback_attach_file;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attach_picture = global::Bit.Android.Resource.String.hockeyapp_feedback_attach_picture;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_button_text = global::Bit.Android.Resource.String.hockeyapp_feedback_attachment_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_error = global::Bit.Android.Resource.String.hockeyapp_feedback_attachment_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_loading = global::Bit.Android.Resource.String.hockeyapp_feedback_attachment_loading;
			global::HockeyApp.Resource.String.hockeyapp_feedback_email_hint = global::Bit.Android.Resource.String.hockeyapp_feedback_email_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_failed_text = global::Bit.Android.Resource.String.hockeyapp_feedback_failed_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_failed_title = global::Bit.Android.Resource.String.hockeyapp_feedback_failed_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_fetching_feedback_text = global::Bit.Android.Resource.String.hockeyapp_feedback_fetching_feedback_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_generic_error = global::Bit.Android.Resource.String.hockeyapp_feedback_generic_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_last_updated_text = global::Bit.Android.Resource.String.hockeyapp_feedback_last_updated_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_max_attachments_allowed = global::Bit.Android.Resource.String.hockeyapp_feedback_max_attachments_allowed;
			global::HockeyApp.Resource.String.hockeyapp_feedback_message_hint = global::Bit.Android.Resource.String.hockeyapp_feedback_message_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_name_hint = global::Bit.Android.Resource.String.hockeyapp_feedback_name_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_refresh_button_text = global::Bit.Android.Resource.String.hockeyapp_feedback_refresh_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_response_button_text = global::Bit.Android.Resource.String.hockeyapp_feedback_response_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_select_file = global::Bit.Android.Resource.String.hockeyapp_feedback_select_file;
			global::HockeyApp.Resource.String.hockeyapp_feedback_select_picture = global::Bit.Android.Resource.String.hockeyapp_feedback_select_picture;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_button_text = global::Bit.Android.Resource.String.hockeyapp_feedback_send_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_generic_error = global::Bit.Android.Resource.String.hockeyapp_feedback_send_generic_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_network_error = global::Bit.Android.Resource.String.hockeyapp_feedback_send_network_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_sending_feedback_text = global::Bit.Android.Resource.String.hockeyapp_feedback_sending_feedback_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_subject_hint = global::Bit.Android.Resource.String.hockeyapp_feedback_subject_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_title = global::Bit.Android.Resource.String.hockeyapp_feedback_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_email_empty = global::Bit.Android.Resource.String.hockeyapp_feedback_validate_email_empty;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_email_error = global::Bit.Android.Resource.String.hockeyapp_feedback_validate_email_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_name_error = global::Bit.Android.Resource.String.hockeyapp_feedback_validate_name_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_subject_error = global::Bit.Android.Resource.String.hockeyapp_feedback_validate_subject_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_text_error = global::Bit.Android.Resource.String.hockeyapp_feedback_validate_text_error;
			global::HockeyApp.Resource.String.hockeyapp_login_email_hint = global::Bit.Android.Resource.String.hockeyapp_login_email_hint;
			global::HockeyApp.Resource.String.hockeyapp_login_headline_text = global::Bit.Android.Resource.String.hockeyapp_login_headline_text;
			global::HockeyApp.Resource.String.hockeyapp_login_headline_text_email_only = global::Bit.Android.Resource.String.hockeyapp_login_headline_text_email_only;
			global::HockeyApp.Resource.String.hockeyapp_login_login_button_text = global::Bit.Android.Resource.String.hockeyapp_login_login_button_text;
			global::HockeyApp.Resource.String.hockeyapp_login_missing_credentials_toast = global::Bit.Android.Resource.String.hockeyapp_login_missing_credentials_toast;
			global::HockeyApp.Resource.String.hockeyapp_login_password_hint = global::Bit.Android.Resource.String.hockeyapp_login_password_hint;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_message = global::Bit.Android.Resource.String.hockeyapp_paint_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_negative_button = global::Bit.Android.Resource.String.hockeyapp_paint_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_neutral_button = global::Bit.Android.Resource.String.hockeyapp_paint_dialog_neutral_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_positive_button = global::Bit.Android.Resource.String.hockeyapp_paint_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_indicator_toast = global::Bit.Android.Resource.String.hockeyapp_paint_indicator_toast;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_clear = global::Bit.Android.Resource.String.hockeyapp_paint_menu_clear;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_save = global::Bit.Android.Resource.String.hockeyapp_paint_menu_save;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_undo = global::Bit.Android.Resource.String.hockeyapp_paint_menu_undo;
			global::HockeyApp.Resource.String.hockeyapp_permission_dialog_negative_button = global::Bit.Android.Resource.String.hockeyapp_permission_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_permission_dialog_positive_button = global::Bit.Android.Resource.String.hockeyapp_permission_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_permission_update_message = global::Bit.Android.Resource.String.hockeyapp_permission_update_message;
			global::HockeyApp.Resource.String.hockeyapp_permission_update_title = global::Bit.Android.Resource.String.hockeyapp_permission_update_title;
			global::HockeyApp.Resource.String.hockeyapp_update_button = global::Bit.Android.Resource.String.hockeyapp_update_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_message = global::Bit.Android.Resource.String.hockeyapp_update_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_negative_button = global::Bit.Android.Resource.String.hockeyapp_update_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_positive_button = global::Bit.Android.Resource.String.hockeyapp_update_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_title = global::Bit.Android.Resource.String.hockeyapp_update_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_update_mandatory_toast = global::Bit.Android.Resource.String.hockeyapp_update_mandatory_toast;
			global::HockeyApp.Resource.String.hockeyapp_update_version_details_label = global::Bit.Android.Resource.String.hockeyapp_update_version_details_label;
			global::HockeyApp.Resource.String.library_name = global::Bit.Android.Resource.String.library_name;
			global::HockeyApp.Resource.Style.HockeyApp_ButtonStyle = global::Bit.Android.Resource.Style.HockeyApp_ButtonStyle;
			global::HockeyApp.Resource.Style.HockeyApp_EditTextStyle = global::Bit.Android.Resource.Style.HockeyApp_EditTextStyle;
			global::HockeyApp.Resource.Style.HockeyApp_SingleLineInputStyle = global::Bit.Android.Resource.Style.HockeyApp_SingleLineInputStyle;
			global::ModernHttpClient.Resource.String.library_name = global::Bit.Android.Resource.String.library_name;
			global::PCLCrypto.Resource.String.ApplicationName = global::Bit.Android.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::Bit.Android.Resource.String.Hello;
			global::Plugin.Fingerprint.Resource.Drawable.fingerprint_white = global::Bit.Android.Resource.Drawable.fingerprint_white;
			global::Plugin.Fingerprint.Resource.Id.fingerprint_btnCancel = global::Bit.Android.Resource.Id.fingerprint_btnCancel;
			global::Plugin.Fingerprint.Resource.Id.fingerprint_txtReason = global::Bit.Android.Resource.Id.fingerprint_txtReason;
			global::Plugin.Fingerprint.Resource.Layout.FingerprintDialog = global::Bit.Android.Resource.Layout.FingerprintDialog;
			global::Splat.Resource.String.library_name = global::Bit.Android.Resource.String.library_name;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.actionBarSize = global::Bit.Android.Resource.Attribute.actionBarSize;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int ahBarColor = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int ahBarLength = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int ahBarWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int ahCircleColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ahDelayMillis = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int ahRadius = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int ahRimColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int ahRimWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int ahSpinSpeed = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int ahText = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int ahTextColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int ahTextSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f07000f
			public const int accent = 2131165199;
			
			// aapt resource value: 0x7f07000b
			public const int darkgray = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int gray = 2131165196;
			
			// aapt resource value: 0x7f070000
			public const int hockeyapp_background_header = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int hockeyapp_background_light = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int hockeyapp_background_white = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int hockeyapp_button_background = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int hockeyapp_button_background_pressed = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int hockeyapp_button_background_selected = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int hockeyapp_text_black = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int hockeyapp_text_light = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int hockeyapp_text_normal = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int hockeyapp_text_white = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int lightgray = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int primary = 2131165198;
			
			// aapt resource value: 0x7f07000a
			public const int white = 2131165194;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int eye = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int eye_slash = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int fa_folder_open = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int fingerprint_white = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int hockeyapp_btn_background = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_errorstatus = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_successstatus = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ion_chevron_right = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ion_plus = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int more = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int roundedbg = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int roundedbgdark = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000f
			public const int button_add_response = 2131230735;
			
			// aapt resource value: 0x7f08000a
			public const int button_attachment = 2131230730;
			
			// aapt resource value: 0x7f080014
			public const int button_login = 2131230740;
			
			// aapt resource value: 0x7f080010
			public const int button_refresh = 2131230736;
			
			// aapt resource value: 0x7f08000b
			public const int button_send = 2131230731;
			
			// aapt resource value: 0x7f080018
			public const int button_update = 2131230744;
			
			// aapt resource value: 0x7f080001
			public const int fingerprint_btnCancel = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int fingerprint_txtReason = 2131230720;
			
			// aapt resource value: 0x7f080006
			public const int input_email = 2131230726;
			
			// aapt resource value: 0x7f080008
			public const int input_message = 2131230728;
			
			// aapt resource value: 0x7f080005
			public const int input_name = 2131230725;
			
			// aapt resource value: 0x7f080013
			public const int input_password = 2131230739;
			
			// aapt resource value: 0x7f080007
			public const int input_subject = 2131230727;
			
			// aapt resource value: 0x7f08001a
			public const int label_author = 2131230746;
			
			// aapt resource value: 0x7f08001b
			public const int label_date = 2131230747;
			
			// aapt resource value: 0x7f08000d
			public const int label_last_updated = 2131230733;
			
			// aapt resource value: 0x7f080002
			public const int label_message = 2131230722;
			
			// aapt resource value: 0x7f08001c
			public const int label_text = 2131230748;
			
			// aapt resource value: 0x7f080016
			public const int label_title = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int label_version = 2131230743;
			
			// aapt resource value: 0x7f08001d
			public const int list_attachments = 2131230749;
			
			// aapt resource value: 0x7f080011
			public const int list_feedback_messages = 2131230737;
			
			// aapt resource value: 0x7f080020
			public const int loadingImage = 2131230752;
			
			// aapt resource value: 0x7f08001e
			public const int loadingProgressBar = 2131230750;
			
			// aapt resource value: 0x7f080021
			public const int loadingProgressWheel = 2131230753;
			
			// aapt resource value: 0x7f08001f
			public const int textViewStatus = 2131230751;
			
			// aapt resource value: 0x7f080012
			public const int text_headline = 2131230738;
			
			// aapt resource value: 0x7f080015
			public const int view_header = 2131230741;
			
			// aapt resource value: 0x7f080019
			public const int web_update_details = 2131230745;
			
			// aapt resource value: 0x7f080009
			public const int wrapper_attachments = 2131230729;
			
			// aapt resource value: 0x7f080004
			public const int wrapper_feedback = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int wrapper_feedback_scroll = 2131230723;
			
			// aapt resource value: 0x7f08000c
			public const int wrapper_messages = 2131230732;
			
			// aapt resource value: 0x7f08000e
			public const int wrapper_messages_buttons = 2131230734;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FingerprintDialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int hockeyapp_activity_expiry_info = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int hockeyapp_activity_feedback = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int hockeyapp_activity_login = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int hockeyapp_activity_update = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int hockeyapp_fragment_update = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int hockeyapp_view_feedback_message = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int loading = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int loadingimage = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int loadingprogress = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int ApplicationName = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int Hello = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int hockeyapp_crash_dialog_app_name_fallback = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int hockeyapp_crash_dialog_message = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int hockeyapp_crash_dialog_negative_button = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int hockeyapp_crash_dialog_neutral_button = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int hockeyapp_crash_dialog_positive_button = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int hockeyapp_crash_dialog_title = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int hockeyapp_dialog_error_message = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int hockeyapp_dialog_error_title = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int hockeyapp_dialog_negative_button = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int hockeyapp_dialog_positive_button = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int hockeyapp_download_failed_dialog_message = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int hockeyapp_download_failed_dialog_negative_button = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int hockeyapp_download_failed_dialog_positive_button = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int hockeyapp_download_failed_dialog_title = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int hockeyapp_error_no_network_message = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int hockeyapp_expiry_info_text = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int hockeyapp_expiry_info_title = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int hockeyapp_feedback_attach_file = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int hockeyapp_feedback_attach_picture = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int hockeyapp_feedback_attachment_button_text = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int hockeyapp_feedback_attachment_error = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int hockeyapp_feedback_attachment_loading = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int hockeyapp_feedback_email_hint = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int hockeyapp_feedback_failed_text = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int hockeyapp_feedback_failed_title = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int hockeyapp_feedback_fetching_feedback_text = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int hockeyapp_feedback_generic_error = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int hockeyapp_feedback_last_updated_text = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int hockeyapp_feedback_max_attachments_allowed = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int hockeyapp_feedback_message_hint = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int hockeyapp_feedback_name_hint = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int hockeyapp_feedback_refresh_button_text = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int hockeyapp_feedback_response_button_text = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int hockeyapp_feedback_select_file = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int hockeyapp_feedback_select_picture = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int hockeyapp_feedback_send_button_text = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int hockeyapp_feedback_send_generic_error = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int hockeyapp_feedback_send_network_error = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int hockeyapp_feedback_sending_feedback_text = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int hockeyapp_feedback_subject_hint = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int hockeyapp_feedback_title = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int hockeyapp_feedback_validate_email_empty = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int hockeyapp_feedback_validate_email_error = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int hockeyapp_feedback_validate_name_error = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int hockeyapp_feedback_validate_subject_error = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int hockeyapp_feedback_validate_text_error = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int hockeyapp_login_email_hint = 2131034161;
			
			// aapt resource value: 0x7f050032
			public const int hockeyapp_login_headline_text = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int hockeyapp_login_headline_text_email_only = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int hockeyapp_login_login_button_text = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int hockeyapp_login_missing_credentials_toast = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int hockeyapp_login_password_hint = 2131034166;
			
			// aapt resource value: 0x7f050037
			public const int hockeyapp_paint_dialog_message = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int hockeyapp_paint_dialog_negative_button = 2131034168;
			
			// aapt resource value: 0x7f050039
			public const int hockeyapp_paint_dialog_neutral_button = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int hockeyapp_paint_dialog_positive_button = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int hockeyapp_paint_indicator_toast = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int hockeyapp_paint_menu_clear = 2131034172;
			
			// aapt resource value: 0x7f05003d
			public const int hockeyapp_paint_menu_save = 2131034173;
			
			// aapt resource value: 0x7f05003e
			public const int hockeyapp_paint_menu_undo = 2131034174;
			
			// aapt resource value: 0x7f05003f
			public const int hockeyapp_permission_dialog_negative_button = 2131034175;
			
			// aapt resource value: 0x7f050040
			public const int hockeyapp_permission_dialog_positive_button = 2131034176;
			
			// aapt resource value: 0x7f050041
			public const int hockeyapp_permission_update_message = 2131034177;
			
			// aapt resource value: 0x7f050042
			public const int hockeyapp_permission_update_title = 2131034178;
			
			// aapt resource value: 0x7f050043
			public const int hockeyapp_update_button = 2131034179;
			
			// aapt resource value: 0x7f050044
			public const int hockeyapp_update_dialog_message = 2131034180;
			
			// aapt resource value: 0x7f050045
			public const int hockeyapp_update_dialog_negative_button = 2131034181;
			
			// aapt resource value: 0x7f050046
			public const int hockeyapp_update_dialog_positive_button = 2131034182;
			
			// aapt resource value: 0x7f050047
			public const int hockeyapp_update_dialog_title = 2131034183;
			
			// aapt resource value: 0x7f050048
			public const int hockeyapp_update_mandatory_toast = 2131034184;
			
			// aapt resource value: 0x7f050049
			public const int hockeyapp_update_version_details_label = 2131034185;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060003
			public const int BitwardenTheme = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int HockeyApp_ButtonStyle = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int HockeyApp_EditTextStyle = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int HockeyApp_SingleLineInputStyle = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int accessibilityservice = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
