project_id_env: _CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
files:
  - source: /src/App/Resources/AppResources.resx
    translation: /src/App/Resources/AppResources.%two_letters_code%.resx
    update_option: update_as_unapproved
    languages_mapping:
      two_letters_code:
        zh-CN: zh-Hans
        zh-TW: zh-Hant
        pt-PT: pt-PT
        pt-BR: pt-BR
        en-GB: en-GB
        en-IN: en-IN
  - source: /store/apple/en/copy.resx
    translation: /store/apple/%two_letters_code%/copy.resx
    update_option: update_as_unapproved
    languages_mapping:
      two_letters_code:
        zh-CN: zh-Hans
        zh-TW: zh-Hant
        pt-PT: pt-PT
        pt-BR: pt-BR
        en-GB: en-GB
        en-IN: en-IN
  - source: /store/google/en/copy.resx
    translation: /store/google/%two_letters_code%/copy.resx
    update_option: update_as_unapproved
    languages_mapping:
      two_letters_code:
        zh-CN: zh-Hans
        zh-TW: zh-Hant
        pt-BR: pt-BR
        pt-PT: pt-PT
        en-GB: en-GB
        en-IN: en-IN
