@file:Suppress("LongParameterList")

package com.bitwarden.network.model

import java.time.Instant

/**
 * Create a mock [SyncResponseJson.Profile] with a given [number].
 */
fun createMockProfile(
    number: Int,
    providerOrganizations: List<SyncResponseJson.Profile.Organization>? = listOf(
        createMockOrganizationNetwork(number = number),
    ),
    isPremiumFromOrganization: Boolean = false,
    shouldForcePasswordReset: Boolean = false,
    avatarColor: String? = "mockAvatarColor-$number",
    isEmailVerified: Boolean = false,
    isTwoFactorEnabled: Boolean = false,
    privateKey: String? = "mockPrivateKey-$number",
    accountKeys: AccountKeysJson? = createMockAccountKeysJson(number = number),
    isPremium: Boolean = false,
    culture: String? = "mockCulture-$number",
    name: String? = "mockName-$number",
    organizations: List<SyncResponseJson.Profile.Organization>? = listOf(
        createMockOrganizationNetwork(number = number),
    ),
    shouldUseKeyConnector: Boolean = false,
    id: String = "mockId-$number",
    masterPasswordHint: String? = "mockMasterPasswordHint-$number",
    email: String? = "mockEmail-$number",
    key: String? = "mockKey-$number",
    securityStamp: String? = "mockSecurityStamp-$number",
    providers: List<SyncResponseJson.Profile.Provider>? = listOf(
        createMockProvider(number = number),
    ),
    creationDate: Instant = Instant.parse("2024-09-13T01:00:00.00Z"),
): SyncResponseJson.Profile =
    SyncResponseJson.Profile(
        providerOrganizations = providerOrganizations,
        isPremiumFromOrganization = isPremiumFromOrganization,
        shouldForcePasswordReset = shouldForcePasswordReset,
        avatarColor = avatarColor,
        isEmailVerified = isEmailVerified,
        isTwoFactorEnabled = isTwoFactorEnabled,
        privateKey = privateKey,
        accountKeys = accountKeys,
        isPremium = isPremium,
        culture = culture,
        name = name,
        legacyOrganizations = organizations,
        newOrganizations = organizations,
        shouldUseKeyConnector = shouldUseKeyConnector,
        id = id,
        masterPasswordHint = masterPasswordHint,
        email = email,
        key = key,
        securityStamp = securityStamp,
        providers = providers,
        creationDate = creationDate,
    )

/**
 * Create a mock [SyncResponseJson.Profile.Organization] with a given [number].
 */
@Suppress("LongMethod")
fun createMockOrganizationNetwork(
    number: Int,
    shouldUsePolicies: Boolean = false,
    isKeyConnectorEnabled: Boolean = false,
    keyConnectorUrl: String? = "mockKeyConnectorUrl-$number",
    type: OrganizationType = OrganizationType.ADMIN,
    seats: UInt? = 1u,
    isEnabled: Boolean = false,
    providerType: ProviderType? = ProviderType.RESELLER,
    maxCollections: UInt? = 1u,
    isSelfHost: Boolean = false,
    permissions: SyncResponseJson.Profile.Permissions = createMockPermissions(),
    providerId: String? = "mockProviderId-$number",
    id: String = "mockId-$number",
    shouldUseGroups: Boolean = false,
    shouldUseDirectory: Boolean = false,
    key: String? = "mockKey-$number",
    providerName: String? = "mockProviderName-$number",
    shouldUsersGetPremium: Boolean = false,
    maxStorageGb: UInt? = 1u,
    identifier: String? = "mockIdentifier-$number",
    use2fa: Boolean = false,
    familySponsorshipToDelete: Boolean? = false,
    userId: String? = "mockUserId-$number",
    shouldUseEvents: Boolean = false,
    familySponsorshipFriendlyName: String? = "mockFamilySponsorshipFriendlyName-$number",
    shouldUseTotp: Boolean = false,
    familySponsorshipLastSyncDate: Instant? = Instant.parse("2023-10-27T12:00:00Z"),
    name: String? = "mockName-$number",
    shouldUseApi: Boolean = false,
    familySponsorshipValidUntil: Instant? = Instant.parse("2023-10-27T12:00:00Z"),
    status: OrganizationStatusType = OrganizationStatusType.CONFIRMED,
    userIsClaimedByOrganization: Boolean = false,
    limitItemDeletion: Boolean = false,
    useSso: Boolean = false,
    useOrganizationDomains: Boolean = false,
    shouldUseKeyConnector: Boolean = false,
    useScim: Boolean = false,
    useCustomPermissions: Boolean = false,
    useResetPassword: Boolean = false,
    useSecretsManager: Boolean = false,
    usePasswordManager: Boolean = false,
    useActivateAutofillPolicy: Boolean = false,
    useAutomaticUserConfirmation: Boolean = false,
    ssoBound: Boolean = false,
    resetPasswordEnrolled: Boolean = false,
    organizationUserId: String? = "mockOrganizationUserId-$number",
    hasPublicAndPrivateKeys: Boolean = false,
    isProviderUser: Boolean = false,
    isMember: Boolean = false,
    familySponsorshipAvailable: Boolean = false,
    productTierType: ProductTierType = ProductTierType.FREE,
    accessSecretsManager: Boolean = false,
    limitCollectionCreation: Boolean = false,
    limitCollectionDeletion: Boolean = false,
    allowAdminAccessToAllCollectionItems: Boolean = false,
    useAccessIntelligence: Boolean = false,
    useAdminSponsoredFamilies: Boolean = false,
    useDisableSmAdsForUsers: Boolean = false,
    isAdminInitiated: Boolean = false,
    ssoEnabled: Boolean = false,
    ssoMemberDecryptionType: MemberDecryptionType? = null,
    usePhishingBlocker: Boolean = false,
    useMyItems: Boolean = false,
): SyncResponseJson.Profile.Organization =
    SyncResponseJson.Profile.Organization(
        shouldUsePolicies = shouldUsePolicies,
        isKeyConnectorEnabled = isKeyConnectorEnabled,
        keyConnectorUrl = keyConnectorUrl,
        type = type,
        seats = seats,
        isEnabled = isEnabled,
        providerType = providerType,
        maxCollections = maxCollections,
        isSelfHost = isSelfHost,
        permissions = permissions,
        providerId = providerId,
        id = id,
        shouldUseGroups = shouldUseGroups,
        shouldUseDirectory = shouldUseDirectory,
        key = key,
        providerName = providerName,
        shouldUsersGetPremium = shouldUsersGetPremium,
        maxStorageGb = maxStorageGb,
        identifier = identifier,
        use2fa = use2fa,
        familySponsorshipToDelete = familySponsorshipToDelete,
        userId = userId,
        shouldUseEvents = shouldUseEvents,
        familySponsorshipFriendlyName = familySponsorshipFriendlyName,
        shouldUseTotp = shouldUseTotp,
        familySponsorshipLastSyncDate = familySponsorshipLastSyncDate,
        name = name,
        shouldUseApi = shouldUseApi,
        familySponsorshipValidUntil = familySponsorshipValidUntil,
        status = status,
        userIsClaimedByOrganization = userIsClaimedByOrganization,
        limitItemDeletion = limitItemDeletion,
        useSso = useSso,
        useOrganizationDomains = useOrganizationDomains,
        shouldUseKeyConnector = shouldUseKeyConnector,
        useScim = useScim,
        useCustomPermissions = useCustomPermissions,
        useResetPassword = useResetPassword,
        useSecretsManager = useSecretsManager,
        usePasswordManager = usePasswordManager,
        useActivateAutofillPolicy = useActivateAutofillPolicy,
        useAutomaticUserConfirmation = useAutomaticUserConfirmation,
        ssoBound = ssoBound,
        resetPasswordEnrolled = resetPasswordEnrolled,
        organizationUserId = organizationUserId,
        hasPublicAndPrivateKeys = hasPublicAndPrivateKeys,
        isProviderUser = isProviderUser,
        isMember = isMember,
        familySponsorshipAvailable = familySponsorshipAvailable,
        productTierType = productTierType,
        accessSecretsManager = accessSecretsManager,
        limitCollectionCreation = limitCollectionCreation,
        limitCollectionDeletion = limitCollectionDeletion,
        allowAdminAccessToAllCollectionItems = allowAdminAccessToAllCollectionItems,
        useAccessIntelligence = useAccessIntelligence,
        useAdminSponsoredFamilies = useAdminSponsoredFamilies,
        useDisableSmAdsForUsers = useDisableSmAdsForUsers,
        isAdminInitiated = isAdminInitiated,
        ssoEnabled = ssoEnabled,
        ssoMemberDecryptionType = ssoMemberDecryptionType,
        usePhishingBlocker = usePhishingBlocker,
        useMyItems = useMyItems,
    )

/**
 * Create a mock set of organization keys with the given [number].
 */
fun createMockOrganizationKeys(
    number: Int,
    organization: SyncResponseJson.Profile.Organization = createMockOrganizationNetwork(
        number = number,
    ),
): Map<String, String> =
    mapOf(organization.id to requireNotNull(organization.key))

/**
 * Create a mock [SyncResponseJson.Profile.Permissions].
 */
fun createMockPermissions(
    shouldManageResetPassword: Boolean = false,
    shouldManagePolicies: Boolean = false,
    accessEventLogs: Boolean = false,
    accessImportExport: Boolean = false,
    accessReports: Boolean = false,
    createNewCollections: Boolean = false,
    editAnyCollection: Boolean = false,
    deleteAnyCollection: Boolean = false,
    manageGroups: Boolean = false,
    manageSso: Boolean = false,
    manageUsers: Boolean = false,
    manageScim: Boolean = false,
): SyncResponseJson.Profile.Permissions =
    SyncResponseJson.Profile.Permissions(
        shouldManageResetPassword = shouldManageResetPassword,
        shouldManagePolicies = shouldManagePolicies,
        accessEventLogs = accessEventLogs,
        accessImportExport = accessImportExport,
        accessReports = accessReports,
        createNewCollections = createNewCollections,
        editAnyCollection = editAnyCollection,
        deleteAnyCollection = deleteAnyCollection,
        manageGroups = manageGroups,
        manageSso = manageSso,
        manageUsers = manageUsers,
        manageScim = manageScim,
    )

/**
 * Create a mock [SyncResponseJson.Profile.Provider] with a given [number].
 */
fun createMockProvider(
    number: Int,
    shouldUseEvents: Boolean = false,
    permissions: SyncResponseJson.Profile.Permissions = createMockPermissions(),
    name: String? = "mockName-$number",
    id: String = "mockId-$number",
    type: Int = 1,
    userId: String? = "mockUserId-$number",
    key: String? = "mockKey-$number",
    isEnabled: Boolean = false,
    status: Int = 1,
): SyncResponseJson.Profile.Provider =
    SyncResponseJson.Profile.Provider(
        shouldUseEvents = shouldUseEvents,
        permissions = permissions,
        name = name,
        id = id,
        type = type,
        userId = userId,
        key = key,
        isEnabled = isEnabled,
        status = status,
    )
