//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bit.App.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bit.App.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new account has been created! You may now log in..
        /// </summary>
        public static string AccountCreated {
            get {
                return ResourceManager.GetString("AccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Login.
        /// </summary>
        public static string AddALogin {
            get {
                return ResourceManager.GetString("AddALogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Login.
        /// </summary>
        public static string AddLogin {
            get {
                return ResourceManager.GetString("AddLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Attachment.
        /// </summary>
        public static string AddNewAttachment {
            get {
                return ResourceManager.GetString("AddNewAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        public static string AnErrorHasOccurred {
            get {
                return ResourceManager.GetString("AnErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Server URL.
        /// </summary>
        public static string ApiUrl {
            get {
                return ResourceManager.GetString("ApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Extension.
        /// </summary>
        public static string AppExtension {
            get {
                return ResourceManager.GetString("AppExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment added.
        /// </summary>
        public static string AttachementAdded {
            get {
                return ResourceManager.GetString("AttachementAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment deleted.
        /// </summary>
        public static string AttachmentDeleted {
            get {
                return ResourceManager.GetString("AttachmentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This attachment is {0} in size. Are you sure you want to download it onto your device?.
        /// </summary>
        public static string AttachmentLargeWarning {
            get {
                return ResourceManager.GetString("AttachmentLargeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator App.
        /// </summary>
        public static string AuthenticatorAppTitle {
            get {
                return ResourceManager.GetString("AuthenticatorAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator Key (TOTP).
        /// </summary>
        public static string AuthenticatorKey {
            get {
                return ResourceManager.GetString("AuthenticatorKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator key added..
        /// </summary>
        public static string AuthenticatorKeyAdded {
            get {
                return ResourceManager.GetString("AuthenticatorKeyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read authenticator key..
        /// </summary>
        public static string AuthenticatorKeyReadError {
            get {
                return ResourceManager.GetString("AuthenticatorKeyReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-fill.
        /// </summary>
        public static string Autofill {
            get {
                return ResourceManager.GetString("Autofill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Scan.
        /// </summary>
        public static string AutofillAlways {
            get {
                return ResourceManager.GetString("AutofillAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always scan the screen for fields and only offer an auto-fill notification if password fields are found. This is the default setting..
        /// </summary>
        public static string AutofillAlwaysDescription {
            get {
                return ResourceManager.GetString("AutofillAlwaysDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the bitwarden accessibility service to auto-fill your logins across apps and the web..
        /// </summary>
        public static string AutofillDescription {
            get {
                return ResourceManager.GetString("AutofillDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to auto-fill or view this login?.
        /// </summary>
        public static string AutofillOrView {
            get {
                return ResourceManager.GetString("AutofillOrView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan When Password Field Focused.
        /// </summary>
        public static string AutofillPasswordField {
            get {
                return ResourceManager.GetString("AutofillPasswordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only scan the screen for fields and offer an auto-fill notification whenever you select a password field. This setting may help conserve battery life..
        /// </summary>
        public static string AutofillPasswordFieldDescription {
            get {
                return ResourceManager.GetString("AutofillPasswordFieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persist Notification.
        /// </summary>
        public static string AutofillPersistNotification {
            get {
                return ResourceManager.GetString("AutofillPersistNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always offer an auto-fill notification and only scan for fields after attempting an auto-fill. This setting may help conserve battery life..
        /// </summary>
        public static string AutofillPersistNotificationDescription {
            get {
                return ResourceManager.GetString("AutofillPersistNotificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-fill Service.
        /// </summary>
        public static string AutofillService {
            get {
                return ResourceManager.GetString("AutofillService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid Ambiguous Characters.
        /// </summary>
        public static string AvoidAmbiguousCharacters {
            get {
                return ResourceManager.GetString("AvoidAmbiguousCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta.
        /// </summary>
        public static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bitwarden.
        /// </summary>
        public static string Bitwarden {
            get {
                return ResourceManager.GetString("Bitwarden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bitwarden App Extension.
        /// </summary>
        public static string BitwardenAppExtension {
            get {
                return ResourceManager.GetString("BitwardenAppExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The easiest way to add new logins to your vault is from the bitwarden App Extension. Learn more about using the bitwarden App Extension by navigating to the &quot;Tools&quot; screen..
        /// </summary>
        public static string BitwardenAppExtensionAlert {
            get {
                return ResourceManager.GetString("BitwardenAppExtensionAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use bitwarden in Safari and other apps to auto-fill your logins..
        /// </summary>
        public static string BitwardenAppExtensionDescription {
            get {
                return ResourceManager.GetString("BitwardenAppExtensionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bitwarden Auto-fill Service.
        /// </summary>
        public static string BitwardenAutofillService {
            get {
                return ResourceManager.GetString("BitwardenAutofillService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The easiest way to add new logins to your vault is from the bitwarden Auto-fill Service. Learn more about using the bitwarden Auto-fill Service by navigating to the &quot;Tools&quot; screen..
        /// </summary>
        public static string BitwardenAutofillServiceAlert {
            get {
                return ResourceManager.GetString("BitwardenAutofillServiceAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the bitwarden accessibility service to auto-fill your logins..
        /// </summary>
        public static string BitwardenAutofillServiceDescription {
            get {
                return ResourceManager.GetString("BitwardenAutofillServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to auto-fill this login? It is not a complete match for &quot;{0}&quot;..
        /// </summary>
        public static string BitwardenAutofillServiceMatchConfirm {
            get {
                return ResourceManager.GetString("BitwardenAutofillServiceMatchConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you see a bitwarden auto-fill notification, you can tap it to launch the auto-fill service..
        /// </summary>
        public static string BitwardenAutofillServiceNotification {
            get {
                return ResourceManager.GetString("BitwardenAutofillServiceNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap this notification to auto-fill a login from your vault..
        /// </summary>
        public static string BitwardenAutofillServiceNotificationContent {
            get {
                return ResourceManager.GetString("BitwardenAutofillServiceNotificationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap this notification to view logins from your vault..
        /// </summary>
        public static string BitwardenAutofillServiceNotificationContentOld {
            get {
                return ResourceManager.GetString("BitwardenAutofillServiceNotificationContentOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Accessibility Settings.
        /// </summary>
        public static string BitwardenAutofillServiceOpenSettings {
            get {
                return ResourceManager.GetString("BitwardenAutofillServiceOpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are searching for an auto-fill login for &quot;{0}&quot;..
        /// </summary>
        public static string BitwardenAutofillServiceSearch {
            get {
                return ResourceManager.GetString("BitwardenAutofillServiceSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. On the Android Accessibility Settings screen, touch &quot;bitwarden&quot; under the Services heading..
        /// </summary>
        public static string BitwardenAutofillServiceStep1 {
            get {
                return ResourceManager.GetString("BitwardenAutofillServiceStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Switch on the toggle and press OK to accept..
        /// </summary>
        public static string BitwardenAutofillServiceStep2 {
            get {
                return ResourceManager.GetString("BitwardenAutofillServiceStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning will happen automatically..
        /// </summary>
        public static string CameraInstructionBottom {
            get {
                return ResourceManager.GetString("CameraInstructionBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point your camera at the QR code..
        /// </summary>
        public static string CameraInstructionTop {
            get {
                return ResourceManager.GetString("CameraInstructionTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open the app &quot;{0}&quot;..
        /// </summary>
        public static string CannotOpenApp {
            get {
                return ResourceManager.GetString("CannotOpenApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Email.
        /// </summary>
        public static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change your email address on the bitwarden.com web vault. Do you want to visit the website now?.
        /// </summary>
        public static string ChangeEmailConfirmation {
            get {
                return ResourceManager.GetString("ChangeEmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Master Password.
        /// </summary>
        public static string ChangeMasterPassword {
            get {
                return ResourceManager.GetString("ChangeMasterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change your master password on the bitwarden.com web vault. Do you want to visit the website now?.
        /// </summary>
        public static string ChangePasswordConfirmation {
            get {
                return ResourceManager.GetString("ChangePasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose File.
        /// </summary>
        public static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon!.
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied!.
        /// </summary>
        public static string Copied {
            get {
                return ResourceManager.GetString("Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied password!.
        /// </summary>
        public static string CopiedPassword {
            get {
                return ResourceManager.GetString("CopiedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied TOTP!.
        /// </summary>
        public static string CopiedTotp {
            get {
                return ResourceManager.GetString("CopiedTotp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied username!.
        /// </summary>
        public static string CopiedUsername {
            get {
                return ResourceManager.GetString("CopiedUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Password.
        /// </summary>
        public static string CopyPassword {
            get {
                return ResourceManager.GetString("CopyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy TOTP.
        /// </summary>
        public static string CopyTotp {
            get {
                return ResourceManager.GetString("CopyTotp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Username.
        /// </summary>
        public static string CopyUsername {
            get {
                return ResourceManager.GetString("CopyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating account....
        /// </summary>
        public static string CreatingAccount {
            get {
                return ResourceManager.GetString("CreatingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Environment.
        /// </summary>
        public static string CustomEnvironment {
            get {
                return ResourceManager.GetString("CustomEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For advanced users. You can specify the base URL of each service independently..
        /// </summary>
        public static string CustomEnvironmentFooter {
            get {
                return ResourceManager.GetString("CustomEnvironmentFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting....
        /// </summary>
        public static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Automatic TOTP Copy.
        /// </summary>
        public static string DisableAutoTotpCopy {
            get {
                return ResourceManager.GetString("DisableAutoTotpCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your login has an authenticator key attached to it, the TOTP verification code is automatically copied to your clipboard whenever you auto-fill the login..
        /// </summary>
        public static string DisableAutoTotpCopyDescription {
            get {
                return ResourceManager.GetString("DisableAutoTotpCopyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Analytics.
        /// </summary>
        public static string DisableGA {
            get {
                return ResourceManager.GetString("DisableGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use analytics to better learn how the app is being used so that we can make it better. All data collection is completely anonymous..
        /// </summary>
        public static string DisableGADescription {
            get {
                return ResourceManager.GetString("DisableGADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete? This cannot be undone..
        /// </summary>
        public static string DoYouReallyWantToDelete {
            get {
                return ResourceManager.GetString("DoYouReallyWantToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Folder.
        /// </summary>
        public static string EditFolder {
            get {
                return ResourceManager.GetString("EditFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Login.
        /// </summary>
        public static string EditLogin {
            get {
                return ResourceManager.GetString("EditLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Us.
        /// </summary>
        public static string EmailUs {
            get {
                return ResourceManager.GetString("EmailUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email us directly to get help or leave feedback..
        /// </summary>
        public static string EmailUsDescription {
            get {
                return ResourceManager.GetString("EmailUsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Automatic Syncing.
        /// </summary>
        public static string EnableAutomaticSyncing {
            get {
                return ResourceManager.GetString("EnableAutomaticSyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your account email address to receive your master password hint..
        /// </summary>
        public static string EnterEmailForHint {
            get {
                return ResourceManager.GetString("EnterEmailForHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your PIN code..
        /// </summary>
        public static string EnterPIN {
            get {
                return ResourceManager.GetString("EnterPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the 6 digit verification code from your authenticator app..
        /// </summary>
        public static string EnterVerificationCodeApp {
            get {
                return ResourceManager.GetString("EnterVerificationCodeApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the 6 digit verification code that was emailed to {0}..
        /// </summary>
        public static string EnterVerificationCodeEmail {
            get {
                return ResourceManager.GetString("EnterVerificationCodeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The environment URLs have been saved..
        /// </summary>
        public static string EnvironmentSaved {
            get {
                return ResourceManager.GetString("EnvironmentSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enable App Extension.
        /// </summary>
        public static string ExntesionReenable {
            get {
                return ResourceManager.GetString("ExntesionReenable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Activated!.
        /// </summary>
        public static string ExtensionActivated {
            get {
                return ResourceManager.GetString("ExtensionActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost done!.
        /// </summary>
        public static string ExtensionAlmostDone {
            get {
                return ResourceManager.GetString("ExtensionAlmostDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable App Extension.
        /// </summary>
        public static string ExtensionEnable {
            get {
                return ResourceManager.GetString("ExtensionEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Safari, find bitwarden using the share icon (hint: scroll to the right on the bottom row of the menu)..
        /// </summary>
        public static string ExtensionInSafari {
            get {
                return ResourceManager.GetString("ExtensionInSafari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get instant access to your passwords!.
        /// </summary>
        public static string ExtensionInstantAccess {
            get {
                return ResourceManager.GetString("ExtensionInstantAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re ready to log in!.
        /// </summary>
        public static string ExtensionReady {
            get {
                return ResourceManager.GetString("ExtensionReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Supported Apps.
        /// </summary>
        public static string ExtensionSeeApps {
            get {
                return ResourceManager.GetString("ExtensionSeeApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your logins are now easily accessable from Safari, Chrome, and other supported apps..
        /// </summary>
        public static string ExtensionSetup {
            get {
                return ResourceManager.GetString("ExtensionSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Safari and Chrome, find bitwarden using the share icon (hint: scroll to the right on the bottom row of the share menu)..
        /// </summary>
        public static string ExtensionSetup2 {
            get {
                return ResourceManager.GetString("ExtensionSetup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the bitwarden icon in the menu to launch the extension..
        /// </summary>
        public static string ExtensionTapIcon {
            get {
                return ResourceManager.GetString("ExtensionTapIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To turn on bitwarden in Safari and other apps, tap the &quot;more&quot; icon on the bottom row of the menu..
        /// </summary>
        public static string ExtensionTurnOn {
            get {
                return ResourceManager.GetString("ExtensionTurnOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Unavailable.
        /// </summary>
        public static string FeatureUnavailable {
            get {
                return ResourceManager.GetString("FeatureUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File a Bug Report.
        /// </summary>
        public static string FileBugReport {
            get {
                return ResourceManager.GetString("FileBugReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an issue at our GitHub repository..
        /// </summary>
        public static string FileBugReportDescription {
            get {
                return ResourceManager.GetString("FileBugReportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Source.
        /// </summary>
        public static string FileSource {
            get {
                return ResourceManager.GetString("FileSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint.
        /// </summary>
        public static string Fingerprint {
            get {
                return ResourceManager.GetString("Fingerprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your fingerprint to verify..
        /// </summary>
        public static string FingerprintDirection {
            get {
                return ResourceManager.GetString("FingerprintDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder created..
        /// </summary>
        public static string FolderCreated {
            get {
                return ResourceManager.GetString("FolderCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder deleted..
        /// </summary>
        public static string FolderDeleted {
            get {
                return ResourceManager.GetString("FolderDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Folder.
        /// </summary>
        public static string FolderNone {
            get {
                return ResourceManager.GetString("FolderNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder updated..
        /// </summary>
        public static string FolderUpdated {
            get {
                return ResourceManager.GetString("FolderUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not correctly formatted..
        /// </summary>
        public static string FormattedIncorrectly {
            get {
                return ResourceManager.GetString("FormattedIncorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Password.
        /// </summary>
        public static string GeneratePassword {
            get {
                return ResourceManager.GetString("GeneratePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get your master password hint.
        /// </summary>
        public static string GetPasswordHint {
            get {
                return ResourceManager.GetString("GetPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Website.
        /// </summary>
        public static string GoToWebsite {
            get {
                return ResourceManager.GetString("GoToWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help and Feedback.
        /// </summary>
        public static string HelpAndFeedback {
            get {
                return ResourceManager.GetString("HelpAndFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons.
        /// </summary>
        public static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Server URL.
        /// </summary>
        public static string IdentityUrl {
            get {
                return ResourceManager.GetString("IdentityUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Logins.
        /// </summary>
        public static string ImportLogins {
            get {
                return ResourceManager.GetString("ImportLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can bulk import logins from the bitwarden.com web vault. Do you want to visit the website now?.
        /// </summary>
        public static string ImportLoginsConfirmation {
            get {
                return ResourceManager.GetString("ImportLoginsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickly bulk import your logins from other password management apps..
        /// </summary>
        public static string ImportLoginsDescription {
            get {
                return ResourceManager.GetString("ImportLoginsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect to the internet before continuing..
        /// </summary>
        public static string InternetConnectionRequiredMessage {
            get {
                return ResourceManager.GetString("InternetConnectionRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Connection Required.
        /// </summary>
        public static string InternetConnectionRequiredTitle {
            get {
                return ResourceManager.GetString("InternetConnectionRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Master Password. Try again..
        /// </summary>
        public static string InvalidMasterPassword {
            get {
                return ResourceManager.GetString("InvalidMasterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PIN. Try again..
        /// </summary>
        public static string InvalidPIN {
            get {
                return ResourceManager.GetString("InvalidPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Sync:.
        /// </summary>
        public static string LastSync {
            get {
                return ResourceManager.GetString("LastSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        public static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 minutes.
        /// </summary>
        public static string LockOption15Minutes {
            get {
                return ResourceManager.GetString("LockOption15Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        public static string LockOption1Hour {
            get {
                return ResourceManager.GetString("LockOption1Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute.
        /// </summary>
        public static string LockOption1Minute {
            get {
                return ResourceManager.GetString("LockOption1Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 hours.
        /// </summary>
        public static string LockOption4Hours {
            get {
                return ResourceManager.GetString("LockOption4Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediately.
        /// </summary>
        public static string LockOptionImmediately {
            get {
                return ResourceManager.GetString("LockOptionImmediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Options.
        /// </summary>
        public static string LockOptions {
            get {
                return ResourceManager.GetString("LockOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in....
        /// </summary>
        public static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login has been deleted..
        /// </summary>
        public static string LoginDeleted {
            get {
                return ResourceManager.GetString("LoginDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Information.
        /// </summary>
        public static string LoginInformation {
            get {
                return ResourceManager.GetString("LoginInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Name.
        /// </summary>
        public static string LoginNoName {
            get {
                return ResourceManager.GetString("LoginNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LogInNoun {
            get {
                return ResourceManager.GetString("LogInNoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in or create a new account to access your secure vault..
        /// </summary>
        public static string LoginOrCreateNewAccount {
            get {
                return ResourceManager.GetString("LoginOrCreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logins.
        /// </summary>
        public static string Logins {
            get {
                return ResourceManager.GetString("Logins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logins for {0}.
        /// </summary>
        public static string LoginsForUri {
            get {
                return ResourceManager.GetString("LoginsForUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Unavailable.
        /// </summary>
        public static string LoginUnavailable {
            get {
                return ResourceManager.GetString("LoginUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login updated..
        /// </summary>
        public static string LoginUpdated {
            get {
                return ResourceManager.GetString("LoginUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out?.
        /// </summary>
        public static string LogoutConfirmation {
            get {
                return ResourceManager.GetString("LogoutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost authenticator app?.
        /// </summary>
        public static string Lost2FAApp {
            get {
                return ResourceManager.GetString("Lost2FAApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Password.
        /// </summary>
        public static string MasterPassword {
            get {
                return ResourceManager.GetString("MasterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation is not correct..
        /// </summary>
        public static string MasterPasswordConfirmationValMessage {
            get {
                return ResourceManager.GetString("MasterPasswordConfirmationValMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The master password is the password you use to access your vault. It is very important that you do not forget your master password. There is no way to recover the password in the event that you forget it..
        /// </summary>
        public static string MasterPasswordDescription {
            get {
                return ResourceManager.GetString("MasterPasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Password Hint (optional).
        /// </summary>
        public static string MasterPasswordHint {
            get {
                return ResourceManager.GetString("MasterPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A master password hint can help you remember your password if you forget it..
        /// </summary>
        public static string MasterPasswordHintDescription {
            get {
                return ResourceManager.GetString("MasterPasswordHintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master password must be at least 8 characters long..
        /// </summary>
        public static string MasterPasswordLengthValMessage {
            get {
                return ResourceManager.GetString("MasterPasswordLengthValMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching Logins.
        /// </summary>
        public static string MatchingLogins {
            get {
                return ResourceManager.GetString("MatchingLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum file size is 100 MB..
        /// </summary>
        public static string MaxFileSize {
            get {
                return ResourceManager.GetString("MaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Numbers.
        /// </summary>
        public static string MinNumbers {
            get {
                return ResourceManager.GetString("MinNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Special.
        /// </summary>
        public static string MinSpecial {
            get {
                return ResourceManager.GetString("MinSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Settings.
        /// </summary>
        public static string MoreSettings {
            get {
                return ResourceManager.GetString("MoreSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must log into the main bitwarden app before you can use the extension..
        /// </summary>
        public static string MustLogInMainApp {
            get {
                return ResourceManager.GetString("MustLogInMainApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Vault.
        /// </summary>
        public static string MyVault {
            get {
                return ResourceManager.GetString("MyVault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New login created..
        /// </summary>
        public static string NewLoginCreated {
            get {
                return ResourceManager.GetString("NewLoginCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no attachments..
        /// </summary>
        public static string NoAttachments {
            get {
                return ResourceManager.GetString("NoAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no favorites in your vault..
        /// </summary>
        public static string NoFavorites {
            get {
                return ResourceManager.GetString("NoFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file chosen.
        /// </summary>
        public static string NoFileChosen {
            get {
                return ResourceManager.GetString("NoFileChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no logins in your vault..
        /// </summary>
        public static string NoLogins {
            get {
                return ResourceManager.GetString("NoLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no logins in your vault for {0}..
        /// </summary>
        public static string NoLoginsForUri {
            get {
                return ResourceManager.GetString("NoLoginsForUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no logins in your vault for this website. Tap to add one..
        /// </summary>
        public static string NoLoginsTap {
            get {
                return ResourceManager.GetString("NoLoginsTap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has two-step login enabled, however, none of the configured two-step providers are supported on this device. Please use a supported device and/or add additional providers that are better supported across devices (such as an authenticator app)..
        /// </summary>
        public static string NoTwoStepAvailable {
            get {
                return ResourceManager.GetString("NoTwoStepAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This login does not have a username or password configured..
        /// </summary>
        public static string NoUsernamePasswordConfigured {
            get {
                return ResourceManager.GetString("NoUsernamePasswordConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, got it!.
        /// </summary>
        public static string OkGotIt {
            get {
                return ResourceManager.GetString("OkGotIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option defaults are set from the main bitwarden app&apos;s password generator tool..
        /// </summary>
        public static string OptionDefaults {
            get {
                return ResourceManager.GetString("OptionDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password generated..
        /// </summary>
        public static string PasswordGenerated {
            get {
                return ResourceManager.GetString("PasswordGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Generator.
        /// </summary>
        public static string PasswordGenerator {
            get {
                return ResourceManager.GetString("PasswordGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically generate strong, unique passwords for your logins..
        /// </summary>
        public static string PasswordGeneratorDescription {
            get {
                return ResourceManager.GetString("PasswordGeneratorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Hint.
        /// </summary>
        public static string PasswordHint {
            get {
                return ResourceManager.GetString("PasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve sent you an email with your master password hint..
        /// </summary>
        public static string PasswordHintAlert {
            get {
                return ResourceManager.GetString("PasswordHintAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to overwrite the current password?.
        /// </summary>
        public static string PasswordOverrideAlert {
            get {
                return ResourceManager.GetString("PasswordOverrideAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible Matching Logins.
        /// </summary>
        public static string PossibleMatchingLogins {
            get {
                return ResourceManager.GetString("PossibleMatchingLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A premium membership is required to use this feature..
        /// </summary>
        public static string PremiumRequired {
            get {
                return ResourceManager.GetString("PremiumRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bitwarden keeps your vault automatically synced by using push notifications. For the best possible experience, please select &quot;Ok&quot; on the following prompt when asked to enable push notifications..
        /// </summary>
        public static string PushNotificationAlert {
            get {
                return ResourceManager.GetString("PushNotificationAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate the App.
        /// </summary>
        public static string RateTheApp {
            get {
                return ResourceManager.GetString("RateTheApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please consider helping us out with a good review!.
        /// </summary>
        public static string RateTheAppDescription {
            get {
                return ResourceManager.GetString("RateTheAppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Store ratings are reset with every new version of bitwarden. Please consider helping us out with a good review!.
        /// </summary>
        public static string RateTheAppDescriptionAppStore {
            get {
                return ResourceManager.GetString("RateTheAppDescriptionAppStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery Code.
        /// </summary>
        public static string RecoveryCodeTitle {
            get {
                return ResourceManager.GetString("RecoveryCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate Password.
        /// </summary>
        public static string RegeneratePassword {
            get {
                return ResourceManager.GetString("RegeneratePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-type Master Password.
        /// </summary>
        public static string RetypeMasterPassword {
            get {
                return ResourceManager.GetString("RetypeMasterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR Code.
        /// </summary>
        public static string ScanQrTitle {
            get {
                return ResourceManager.GetString("ScanQrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search vault.
        /// </summary>
        public static string SearchVault {
            get {
                return ResourceManager.GetString("SearchVault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Development Progress.
        /// </summary>
        public static string SeeDevProgress {
            get {
                return ResourceManager.GetString("SeeDevProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-hosted Environment.
        /// </summary>
        public static string SelfHostedEnvironment {
            get {
                return ResourceManager.GetString("SelfHostedEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the base URL of your on-premise hosted bitwarden installation..
        /// </summary>
        public static string SelfHostedEnvironmentFooter {
            get {
                return ResourceManager.GetString("SelfHostedEnvironmentFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send verification code email again.
        /// </summary>
        public static string SendVerificationCodeAgain {
            get {
                return ResourceManager.GetString("SendVerificationCodeAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server URL.
        /// </summary>
        public static string ServerUrl {
            get {
                return ResourceManager.GetString("ServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set PIN.
        /// </summary>
        public static string SetPIN {
            get {
                return ResourceManager.GetString("SetPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a 4 digit PIN code to unlock the app with..
        /// </summary>
        public static string SetPINDirection {
            get {
                return ResourceManager.GetString("SetPINDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Your Vault.
        /// </summary>
        public static string ShareVault {
            get {
                return ResourceManager.GetString("ShareVault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an organization to securely share your logins with other users..
        /// </summary>
        public static string ShareVaultDescription {
            get {
                return ResourceManager.GetString("ShareVaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting....
        /// </summary>
        public static string Submitting {
            get {
                return ResourceManager.GetString("Submitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing....
        /// </summary>
        public static string Syncing {
            get {
                return ResourceManager.GetString("Syncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing complete..
        /// </summary>
        public static string SyncingComplete {
            get {
                return ResourceManager.GetString("SyncingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing failed..
        /// </summary>
        public static string SyncingFailed {
            get {
                return ResourceManager.GetString("SyncingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Vault Now.
        /// </summary>
        public static string SyncVaultNow {
            get {
                return ResourceManager.GetString("SyncVaultNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You.
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch ID.
        /// </summary>
        public static string TouchID {
            get {
                return ResourceManager.GetString("TouchID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        public static string Translations {
            get {
                return ResourceManager.GetString("Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-step Login.
        /// </summary>
        public static string TwoStepLogin {
            get {
                return ResourceManager.GetString("TwoStepLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-step login makes your account more secure by requiring you to verify your login with another device such as a security key, authenticator app, SMS, phone call, or email. Two-step login can be enabled on the bitwarden.com web vault. Do you want to visit the website now?.
        /// </summary>
        public static string TwoStepLoginConfirmation {
            get {
                return ResourceManager.GetString("TwoStepLoginConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-step Login Options.
        /// </summary>
        public static string TwoStepLoginOptions {
            get {
                return ResourceManager.GetString("TwoStepLoginOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download file..
        /// </summary>
        public static string UnableToDownloadFile {
            get {
                return ResourceManager.GetString("UnableToDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device cannot open this type of file..
        /// </summary>
        public static string UnableToOpenFile {
            get {
                return ResourceManager.GetString("UnableToOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock with {0}.
        /// </summary>
        public static string UnlockWith {
            get {
                return ResourceManager.GetString("UnlockWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock with PIN Code.
        /// </summary>
        public static string UnlockWithPIN {
            get {
                return ResourceManager.GetString("UnlockWithPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot use this feature until you update your encryption key..
        /// </summary>
        public static string UpdateKey {
            get {
                return ResourceManager.GetString("UpdateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI.
        /// </summary>
        public static string URI {
            get {
                return ResourceManager.GetString("URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another two-step login method.
        /// </summary>
        public static string UseAnotherTwoStepMethod {
            get {
                return ResourceManager.GetString("UseAnotherTwoStepMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Fingerprint to Unlock.
        /// </summary>
        public static string UseFingerprintToUnlock {
            get {
                return ResourceManager.GetString("UseFingerprintToUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating.
        /// </summary>
        public static string Validating {
            get {
                return ResourceManager.GetString("Validating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string ValidationFieldRequired {
            get {
                return ResourceManager.GetString("ValidationFieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been copied..
        /// </summary>
        public static string ValueHasBeenCopied {
            get {
                return ResourceManager.GetString("ValueHasBeenCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code (TOTP).
        /// </summary>
        public static string VerificationCodeTotp {
            get {
                return ResourceManager.GetString("VerificationCodeTotp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send verification email. Try again..
        /// </summary>
        public static string VerificationEmailNotSent {
            get {
                return ResourceManager.GetString("VerificationEmailNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification email sent..
        /// </summary>
        public static string VerificationEmailSent {
            get {
                return ResourceManager.GetString("VerificationEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Fingerprint.
        /// </summary>
        public static string VerifyFingerprint {
            get {
                return ResourceManager.GetString("VerifyFingerprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Master Password.
        /// </summary>
        public static string VerifyMasterPassword {
            get {
                return ResourceManager.GetString("VerifyMasterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify PIN.
        /// </summary>
        public static string VerifyPIN {
            get {
                return ResourceManager.GetString("VerifyPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Login.
        /// </summary>
        public static string ViewLogin {
            get {
                return ResourceManager.GetString("ViewLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Our Website.
        /// </summary>
        public static string VisitOurWebsite {
            get {
                return ResourceManager.GetString("VisitOurWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit our website to get help, news, email us, and/or learn more about how to use bitwarden..
        /// </summary>
        public static string VisitOurWebsiteDescription {
            get {
                return ResourceManager.GetString("VisitOurWebsiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bitwarden Web Vault.
        /// </summary>
        public static string WebVault {
            get {
                return ResourceManager.GetString("WebVault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your logins from any web browser with the bitwarden web vault..
        /// </summary>
        public static string WebVaultDescription {
            get {
                return ResourceManager.GetString("WebVaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Vault Server URL.
        /// </summary>
        public static string WebVaultUrl {
            get {
                return ResourceManager.GetString("WebVaultUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold your YubiKey NEO against the back of the device to continue..
        /// </summary>
        public static string YubiKeyInstruction {
            get {
                return ResourceManager.GetString("YubiKeyInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YubiKey NEO Security Key.
        /// </summary>
        public static string YubiKeyTitle {
            get {
                return ResourceManager.GetString("YubiKeyTitle", resourceCulture);
            }
        }
    }
}
