// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Bit.iOS
{
	public partial class LaunchScreenViewController : UIViewController
	{
		public LaunchScreenViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
