/**
 * Contains build information provided by the CI build process.
 *
 * **WARNING:** This object is automatically generated by the CI scripts.
 * Do not modify this file directly unless you are also updating the
 * corresponding CI scripts that generate it.
 */
object CIBuildInfo {
    /**
     * Contains build information generated by the CI process.
     */
    val info: List<Pair<String, String>> = emptyList()
}
