name: 'Setup Android Build'
description: 'Setup Android build environment with Gradle, Ruby, and Fastlane'
inputs:
  java-version:
    description: 'Java version to use'
    required: false
    default: '21'
runs:
  using: 'composite'
  steps:
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5.0.1

    - name: Configure Ruby
      uses: ruby/setup-ruby@44511735964dcb71245e7e55f72539531f7bc0eb # v1.257.0
      with:
        bundler-cache: true

    - name: Configure JDK
      uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
      with:
        distribution: "temurin"
        java-version: ${{ inputs.java-version }}

    - name: Install Fastlane
      shell: bash
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
