name: 'Setup Android Build'
description: 'Setup Android build environment with Gradle, Ruby, and Fastlane'
inputs:
  java-version:
    description: 'Java version to use'
    required: false
    default: '21'
runs:
  using: 'composite'
  steps:
    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

    - name: Cache Gradle files
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-v2-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/libs.versions.toml') }}
        restore-keys: |
          ${{ runner.os }}-gradle-v2-

    - name: Cache build output
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: |
          ${{ github.workspace }}/build-cache
        key: ${{ runner.os }}-build-cache-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-

    - name: Configure Ruby
      uses: ruby/setup-ruby@44511735964dcb71245e7e55f72539531f7bc0eb # v1.257.0
      with:
        bundler-cache: true

    - name: Configure JDK
      uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
      with:
        distribution: "temurin"
        java-version: ${{ inputs.java-version }}

    - name: Install Fastlane
      shell: bash
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
