// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;

namespace Bit.iOS.ShareExtension
{
    public partial class ExtensionNavigationController : UINavigationController
	{
		public ExtensionNavigationController (IntPtr handle) : base (handle)
		{
		}

        public override UIViewController PopViewController(bool animated)
        {
            TopViewController?.Dispose();
            return base.PopViewController(animated);

        }

        public override void DismissModalViewController(bool animated)
        {
            ModalViewController?.Dispose();
            base.DismissModalViewController(animated);
        }
    }
}
