name: Create GitHub Release

on:
  workflow_dispatch:
    inputs:
      artifact-run-id:
        description: "GitHub Action Run ID containing artifacts"
        required: true
        type: string
      release-ticket-id:
        description: "Release Ticket ID - e.g. RELEASE-1762"
        required: true
        type: string

jobs:
  jobs:
  deploy:
    name: Trigger publish via deploy repo
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - name: Trigger publish
        uses: bitwarden/gh-actions/trigger-actions@main
        with:
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          artifact_run_id: ${{ github.event.inputs.artifact-run-id }}
          release_ticket_id: ${{ github.event.inputs.release-ticket-id }} }}
          task: release-android
          description: "Trigger release of Android artifacts"
