name: Publish Password Manager GitHub Release as newest

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1-5'

permissions:
  contents: write
  actions: read

jobs:
  publish-release-password-manager:
    name: Publish Password Manager Release
    uses: bitwarden/gh-actions/.github/workflows/_publish-mobile-github-release.yml@main
    with:
      release_name: "Password Manager"
      workflow_name: "publish-github-release-passoword-manager.yml"
      credentials_filename: "play_creds.json"
      check_release_command: >
        bundle exec fastlane android getLatestVersion serviceCredentialsFile:$CREDENTIALS_PATH
    secrets: inherit
