
name: Publish

on:
  workflow_dispatch:

permissions: {}

jobs:
    publish:
      runs-on: ubuntu-24.04
      name: Promote build to Production in Play Store

      steps:
        - name: TEST STEP
          run: exit 0
