name: Publish Authenticator GitHub Release as newest

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1-5'

permissions:
  contents: write
  actions: read
jobs:
  publish-release-authenticator:
    name: Publish Authenticator Release
    uses: bitwarden/gh-actions/.github/workflows/_publish-mobile-github-release.yml@main
    with:
      release_name: "Authenticator"
      workflow_name: "publish-github-release-authenticator.yml"
      credentials_filename: "authenticator_play_store-creds.json"
      check_release_command: >
        bundle exec fastlane android getLatestPlayStoreVersion package_name:com.bitwarden.authenticator track:production
    secrets: inherit
