name: Publish Password Manager GitHub Release as newest

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1-5'

jobs:
  publish-release-password-manager:
    uses: ./.github/workflows/_publish-github-release.yml
    with:
      release_name: "Password Manager"
      workflow_name: "publish-github-release.yml"
      credentials_filename: "play_creds.json"
      check_release_command: >
        bundle exec fastlane android getLatestVersion serviceCredentialsFile:$CREDENTIALS_PATH
    secrets:
      AZURE_KV_CI_SERVICE_PRINCIPAL: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}

  publish-release-authenticator:
    uses: ./.github/workflows/_publish-github-release.yml
    with:
      release_name: "Authenticator"
      workflow_name: "publish-github-release.yml"
      credentials_filename: "play_creds.json"
      check_release_command: >
        bundle exec fastlane android getLatestVersion serviceCredentialsFile:$CREDENTIALS_PATH
    secrets:
      AZURE_KV_CI_SERVICE_PRINCIPAL: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}
