name: Publish Password Manager GitHub Release as newest

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1-5'

permissions:
  contents: write
  actions: read

jobs:
  publish-release-password-manager:
    name: Publish Password Manager Release
    uses: ./.github/workflows/_publish-github-release.yml
    with:
      release_name: "Password Manager"
      workflow_name: "publish-github-release-passoword-manager.yml"
      credentials_filename: "play_creds.json"
      check_release_command: >
        bundle exec fastlane android getLatestPlayStoreVersion package_name:com.x8bit.bitwarden track:production
    secrets: inherit
