name: Test SDK Update

on:
  workflow_dispatch:
    inputs:
      sdk-package:
        description: "SDK Package"
        default: "com.bitwarden:sdk-android.dev"
      sdk-version:
        description: "SDK Version"
        default: "1.0.0-2577-fix-wasm-import"

env:
  _JAVA_VERSION: 17

jobs:
  test:
    name: Test SDK Update
    runs-on: ubuntu-24.04
    permissions:
      packages: read

    steps:
      - name: Check out repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4.4.1

      - name: Cache Gradle files
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-v2-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-v2-

      - name: Cache build output
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            ${{ github.workspace }}/build-cache
          key: ${{ runner.os }}-build-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Configure Ruby
        uses: ruby/setup-ruby@bb6434c747fa7022e12fa1cae2a0951fcffcff26 # v1.253.0
        with:
          bundler-cache: true

      - name: Configure JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: "temurin"
          java-version: ${{ env._JAVA_VERSION }}

      - name: Install Fastlane
        run: |
          gem install bundler:2.2.27
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Update SDK Version
        env:
          _SDK_PACKAGE: ${{ inputs.sdk-package }}
          _SDK_VERSION: ${{ inputs.sdk-version }}
        run: |
          ./scripts/update-sdk-version.sh "$_SDK_PACKAGE" "$_SDK_VERSION"

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Used in settings.gradle.kts to download the SDK from GitHub Maven Packages
        run: |
          bundle exec fastlane assembleDebugApks
          bundle exec fastlane buildAuthenticatorDebug
